name: Deploy WordPress via FTP

on:
  push:
    branches:
      - main # or master

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
        
    # This is the action for deployment
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}       # ***SECRETS***
        username: ${{ secrets.FTP_USERNAME }}   # ***SECRETS***
        password: ${{ secrets.FTP_PASSWORD }}   # ***SECRETS***
        server-dir: /htdocs/                   # Check your host's path
        
        # This parameter enables efficient file syncing.
        # It's set by default, so you don't need to change anything!
        # The action tracks which files it has already uploaded.
        # state-name: .ftp-deploy-sync-state.json 
        
        # âœ… EXCLUSION LIST: These files/folders will be skipped entirely.
        exclude: |
          .git/
          .github/
          node_modules/
          vendor/
          wp-admin/**
          wp-includes/**
          wp-content/plugins/disable-wordpress-updates/**
